R9 Reactube Nivel 2 (estilos)
silviapio/r9-reactube pull request #3
Opened 2021-03-07 15:16 UTC by silviapio

Nivel 2 maquetado, finalmente! :)

2021-03-12 18:17 UTC, itacademyonline requested changes

2021-03-12 18:17 UTC, itacademyonline commented on package.json
>      "@testing-library/react": "^11.2.5",
Estas dependencias son de desarrollo (testing), por tanto deberían de estar en el nodo devDependencies, en lugar d dependencies

2021-03-12 18:17 UTC, itacademyonline commented on src/components/App.js
> +import { BrowserRouter as Router, Route, Switch, Link } from'react-router-dom';
Falta un espacio después del from.

2021-03-12 18:17 UTC, itacademyonline commented on src/components/App.js
> +import { FaYoutube } from 'react-icons/fa'
Falta un ; y para que todo esté correctamente ordenado, los import de nodemodules deberían estar antes que los imports de los ficheros.

2021-03-12 18:17 UTC, itacademyonline commented on src/components/App.js
> +                        <Menu />
La etiqueta <Menu /> está mal identada. Tendría que estar más a la izquierda.

2021-03-12 18:17 UTC, itacademyonline commented on src/components/App.js
> +                            <FaYoutube />
**FaYoutube** y **h4** son hijos del div y no están identados. ¿Usas un formateador automático para el identado?

2021-03-12 18:17 UTC, itacademyonline commented on src/components/App.js
> +                        <Route path={"/"} exact component={Home}></Route>
Las llaves no hacen falta porque dentro del atributo path no estás poniendo ninguna variable.

2021-03-12 18:17 UTC, itacademyonline commented on src/components/App.js
> +                    <Link to='/'>
En general, usas comillas dobles para los atributos (y es correcto), pero aquí estás usando comillas simples.

2021-03-12 18:17 UTC, itacademyonline commented on src/components/App.js
> +                        <Route path={"/videoDetail/:id"} component={VideoDetailPage}></Route>
Puedes terminar la etiqueta de manera más simple usando una contrabarra:
```html
 <Route path="/videoDetail/:id" component={VideoDetailPage} />

2021-03-12 18:17 UTC, itacademyonline commented on src/components/App.styles.js
> +import { smallTablet } from '../utils/mediaQueries';
Estás importando dos veces del mismo archivo. Deberías haber usado:
```js
import { smallTablet, mediumPhone  } from '../utils/mediaQueries';

2021-03-12 18:17 UTC, itacademyonline commented on src/components/App.styles.js
> +      }
La llave no está bien identada. Puedes configurar el visual studio para que te formatee cada vez que salvas:

https://pablomonteserin.com/curso/visual-studio-code/#block-622e8660-6507-4a02-ad74-c62a7c1fb6ae:~:text=Editamos%20el%20objeto%20JSON%20que%20aparece.

2021-03-12 18:17 UTC, itacademyonline commented on src/components/App.styles.js
> +                margin: 0 0 0 4px;
Al final, te hubiese bastado con un margin-left

2021-03-12 18:17 UTC, itacademyonline commented on src/components/FavoriteToggler.js
> +const FavoriteToggler = ({onFavToggle, isFavorite}) => (
No está bien identado:
```js
<FavoriteButton onClick={onFavToggle} isfavorite={isFavorite}>
    {isFavorite ? <FaHeart/> : <FaRegHeart/>}
</FavoriteButton>

2021-03-12 18:17 UTC, itacademyonline commented on src/components/FavoriteToggler.js
> +import { FaHeart, FaRegHeart } from 'react-icons/fa';
Aquí ocurre el mismo problema con los imports, los node_modules deberían ir idealmente los primeros.

2021-03-12 18:17 UTC, itacademyonline commented on src/components/FavoriteToggler.styles.js
> +        :hover {
Yo creo que el hover no funciona, no? falta el &:
```css
&:hover

2021-03-12 18:17 UTC, itacademyonline commented on src/components/Favorites.js
> +      }
Falta ; al final de la función.

2021-03-12 18:17 UTC, itacademyonline commented on src/components/Favorites.js
> +      }
Falta ; al final de la función.

2021-03-12 18:17 UTC, itacademyonline commented on src/components/Favorites.js
> +      />);
El paréntesis cerrando debería estar en la siguiente línea.

2021-03-12 18:17 UTC, itacademyonline commented on src/components/Home.js
> +function App() {
No has usado una función flecha cuando en el resto de de código siempre usas función flecha.

2021-03-12 18:17 UTC, itacademyonline commented on src/components/Home.js
> +    videos.forEach(video => {
Estás mutando los videos. Para estos casos, lo correcto es usar un map y almacenar el valor devuelto en una nueva variable.

2021-03-12 18:17 UTC, itacademyonline commented on src/components/Home.js
> +    setVideos([...videos]);
Te hubiese bastado usar:
```js
setVideos(videos);

2021-03-12 18:17 UTC, itacademyonline commented on src/components/Home.js
> +  useEffect(() => localStorage.setItem("savedSearches", JSON.stringify(searchHistory)), [searchHistory]);
Ya que tienes un archivo de utils, hubiese sido más correcto definir una función para salvar los datos en el local storage (setL o algo así), que hiciese todas las conversiones necesarias.

2021-03-12 18:17 UTC, itacademyonline commented on src/components/Home.js
> +            id: { videoId: videoItem.id }
Si ya tienes el id en videoItem, es un poco raro que en vez de almacenarlo directamente en la propieadad id, crees una estructura {videoId: videoItem.id}. Hubiese puesto directamente id:id

2021-03-12 18:17 UTC, itacademyonline commented on src/components/Home.js
> +        videoList.forEach(video => {
Cuando quieres cambiar los valores de un array, utilizas un map para almacenar el valor devuelto de los items modificados, nunca debes usar un forEach para estas cosa,  ya que mutas el array original.

2021-03-12 18:17 UTC, itacademyonline commented on src/components/Home.js
> +  }
Falta ;

2021-03-12 18:17 UTC, itacademyonline commented on src/components/Home.js
> +  }
Falta ;

2021-03-12 18:17 UTC, itacademyonline commented on src/components/Home.js
> +            className="horizontal5home"  />
Sobra un espacio en blanco.

2021-03-12 18:17 UTC, itacademyonline commented on src/components/Home.js
> +            loading={isLoading}
Las props están mal identadas, deben quedar por dentro del componente.

2021-03-12 18:17 UTC, itacademyonline commented on src/components/Home.js
> +                {searchHistory.map( (historyEntry, i) =>
Sobra el espacio en blanco entr los paréntesis.

2021-03-12 18:17 UTC, itacademyonline commented on src/components/Menu.js
> +            <Link to='/favorites'>
Comillas dobles.

2021-03-12 18:17 UTC, itacademyonline commented on src/components/SearchBar.js
> +                disabled={loading} />
El símbolo de cierre debería ir en la siguiente línea />

2021-03-12 18:17 UTC, itacademyonline commented on src/components/SearchBar.styles.js
> +
Sobra un salto de línea.

2021-03-12 18:17 UTC, itacademyonline commented on src/components/SearchHistory.js
> +        let videosToDisplay;
Cuando usamos un let muchas veces es símbolo de que no estamos haciendo algo bien. Por ejemplo, en este caso hubiese quedado más limpio usar un operador ternario.

```js
const videosToDisplay = localData
    ? JSON.parse(localData).map(searchItem => searchItem.searchedVideos).flat()
    : [];

2021-03-12 18:17 UTC, itacademyonline commented on src/components/SearchHistory.js
> +    useEffect(() => {localStorage.setItem("viewedVideos", JSON.stringify(recentlyViewed))}, [recentlyViewed]);
Como te comenté antes, hubiese definido una función para salvar en el localStorage haciendo el stringify

2021-03-12 18:17 UTC, itacademyonline commented on src/components/SearchHistory.js
> +        recentlyViewed.forEach(video => {
Vuelves a usar el forEach para mutar (ಥ﹏ಥ). Mejor usar un map y almacenar el valor devuelto.

2021-03-12 18:17 UTC, itacademyonline commented on src/components/SearchHistory.js
> +        setRecentlyViewed([
Esto también lo hiciste mal antes, mejor así:
```js
setRecentlyViewed(recentlyViewed);

2021-03-12 18:17 UTC, itacademyonline commented on src/components/SearchHistory.js
> +      }
Mal identado y falta un ;

2021-03-12 18:17 UTC, itacademyonline commented on src/components/SearchHistory.js
> +            {recentlyViewed.length === 0 && lastSearchedVideos.length === 0 ?
!!recentlyViewed.length → tiene items
!recentlyViewed.length → no tiene items

2021-03-12 18:17 UTC, itacademyonline commented on src/components/SearchHistoryItem.js
> +const SearchHistoryItem = (props) => {
Aquí hubiese hecho una deconstrucción de las props.

2021-03-12 18:17 UTC, itacademyonline commented on src/components/VideoDetail.js
> +const VideoDetail = ({ video, video: { id: { videoId }, snippet: { title, description } }, onFavToggle, isFavorite }) => {
Se puede separar en varias líneas para que sea más legible:
```js
const VideoDetail = ({ 
video, 
video: { id: { videoId }, 
snippet: { title, description } }, 
onFavToggle, isFavorite,
}) => {

2021-03-12 18:17 UTC, itacademyonline commented on src/components/VideoDetailPage.js
> +                updatedVideos.unshift(videoToDisplay);
Puedes evitar el método **unshift** usando el mismo spread de arriba:

```js

const updatedVideos = [videoToDisplay, ...recentlyViewed];

2021-03-12 18:17 UTC, itacademyonline commented on src/components/VideoDetailPage.js
> +            videoList.forEach(video => video.isFavorite = isVideoFavorite(video, favorites));
Vuelves a usar el forEach para mutar .·´¯`(>▂<)´¯`·.

2021-03-12 18:17 UTC, itacademyonline commented on src/components/VideoDetailPage.js
> +    const wasVideoDisplayedAlready = myVideoId => {
Esto se podría haber resuelto en una sola línea:
```js
const wasVideoDisplayedAlready = myVideoId => recentlyViewed.filter(({ id })=> id.videoId === myVideoId).length === 1;

2021-03-12 18:17 UTC, itacademyonline commented on src/components/VideoDetailPage.js
> +        .then((response) =>{
Falta un espacio después de la arrow function.

2021-03-12 18:17 UTC, itacademyonline commented on src/components/VideoList.js
> +    const handleSelect = key => () => {
Esta función es innecesaria.

2021-03-12 18:17 UTC, itacademyonline commented on src/components/VideoList.js
> +                        onSelect={handleSelect(video.id.videoId)}
handleSelect => onSelect

2021-03-12 18:17 UTC, itacademyonline commented on src/components/VideoList.js
> +    let videosToDisplay;
Se podría refactorizar de esta manera:

```js
const videosToDisplay = videos.filter(video => video.snippet);

const isXPage = type === "lastSearchesHistoryPage" || type === "favoritesHome";
const isFavoritesPage = type === "favoritesPage";

const limit = (isFavoritesPage || isXPage) ? isXPage ? 10 : 5 : 0;

const videos = !limit ? videosToDisplay : videosToDisplay.slice(0, limit);

2021-03-12 18:17 UTC, itacademyonline commented on src/components/VideoList.js
> +            { (headerStyle === "topHeader" || headerStyle === "lastSearchesHistoryPage") ? <h4>{header}</h4> :
Se vería más legible de esta manera:

```js

{(headerStyle === "topHeader" || headerStyle === "lastSearchesHistoryPage")
   ? <h4>{header}</h4>
   : <h5>{header}</h5>
}

2021-03-12 18:17 UTC, itacademyonline commented on src/components/VideoList.styles.js
> +    opacity: ${props => props.loading && "0.2"};
Como lo tienes ahora si **loading** fuese falso se está quedando guardado el 'false' en la propiedad **opacity**. Deberías ponerlo mejor:

```css
    opacity: ${props => props.loading ? 0.2 : 1};

2021-03-12 18:17 UTC, itacademyonline commented on src/services/youtube.js
> +        return axios.get('https://www.googleapis.com/youtube/v3/search', {
Las url de las APIs en las que buscas resultados quedarían mejor guardadas en variables, para evitar repetir la url completa de ese endpoint cada vez que haces una petición.

2021-03-12 18:17 UTC, itacademyonline commented on src/utils/localStorageUtils.js
> +}
Falta un ;

2021-03-12 18:17 UTC, itacademyonline commented on src/utils/favoritesUtils.js
> +    let videoFound = favorites.filter(favoritesItem => favoritesItem.id.videoId === myVideo.id.videoId);
Este es el mismo caso que hemos visto anteriormente, donde puedes hacerlo en una línea y evitando el 'let'

2021-03-12 18:17 UTC, itacademyonline commented on src/utils/favoritesUtils.js
> +        video.isFavorite = true;
Por norma general no deberías mutar las variables y menos si vienen por parámetro. Esto lleva fácilmente a error como el de 'quién ha cambiado un objeto' siendo varias las funciones que mutan a éste.

2021-03-17 14:41 UTC, silviapio commented on src/components/App.js
> +import { BrowserRouter as Router, Route, Switch, Link } from'react-router-dom';
cierto, bien visto

2021-03-17 14:41 UTC, silviapio commented on src/components/App.js
> +import { FaYoutube } from 'react-icons/fa'
ok!

2021-03-17 14:43 UTC, silviapio commented on src/components/App.js
> +                        <Menu />
Me imagino que te refieres al `<Menu />` , si es eso lo he corregido. gracias

2021-03-17 14:45 UTC, silviapio commented on src/components/App.js
> +                            <FaYoutube />
No, solamente uso la funcionalidad de VS Code (shift+alt+F) pero la verdad es que no es muy cómodo si tienes muchos archivos, porque deberías ejecutarlo cada vez que guardas y por cada uno de los ficheros...

2021-03-17 14:49 UTC, silviapio commented on src/components/App.js
> +                        <Route path={"/"} exact component={Home}></Route>
uuuhhh es cierto, las he puesto en automático pero no tienen porque estar. También he quitado el código comentado de la línea 32, se había quedado ahí por error. gracias

2021-03-17 14:50 UTC, silviapio commented on src/components/App.js
> +                    <Link to='/'>
Tienes razón, el estilo tiene que ser uniforme!

2021-03-17 14:54 UTC, silviapio commented on src/components/App.js
> +                        <Route path={"/videoDetail/:id"} component={VideoDetailPage}></Route>
pues sí. gracias!

2021-03-17 14:54 UTC, silviapio commented on src/components/App.styles.js
> +import { smallTablet } from '../utils/mediaQueries';
aix! sí. hecho

2021-03-17 15:01 UTC, silviapio commented on src/components/App.styles.js
> +      }
Genial!! esto me va a ahorrar mucho tiempo. gracias

2021-03-17 15:02 UTC, silviapio commented on src/components/App.styles.js
> +                margin: 0 0 0 4px;
cierto. cambiado!

2021-03-17 15:04 UTC, silviapio commented on src/components/FavoriteToggler.js
> +const FavoriteToggler = ({onFavToggle, isFavorite}) => (
ok!

2021-03-17 15:05 UTC, silviapio commented on src/components/FavoriteToggler.js
> +import { FaHeart, FaRegHeart } from 'react-icons/fa';
cierto, ok

2021-03-17 15:10 UTC, silviapio commented on src/components/FavoriteToggler.styles.js
> +        :hover {
funciona de las 2 maneras en este caso... no me preguntes el porque :-P

2021-03-17 15:11 UTC, silviapio commented on src/components/Favorites.js
> +      }
correcto; y además podía estar todo en la misma línea. Lo he corregido así:
`const handleVideoSelect = myVideoId => history.push(`/videoDetail/${myVideoId}`);`

2021-03-17 15:12 UTC, silviapio commented on src/components/Favorites.js
> +      }
ok corregido!

2021-03-17 15:13 UTC, silviapio commented on src/components/Favorites.js
> +      />);
ok, corregido

2021-03-17 15:16 UTC, silviapio commented on src/components/Home.js
> +function App() {
corregido. Se había quedado como "souvenir" del hecho que esta en el nivel 1 era App (y de hecho, se ha quedado el nombre también, que aunque funcione porque luego lo importo como Home, se ve un poco "antiestético". He cambiado eso también!)

2021-03-17 16:34 UTC, silviapio commented on src/components/Home.js
> +    videos.forEach(video => {
correcto. También me he dado cuenta de que tenía una función creada en `utils/favoritesUtils.js` que comprueba si el video está en favoritos, y la he utilizado para no repetir código. ha quedado así:
`useEffect(() => {
    const newVideos = videos.map(video => {
      return {
        ...video,
        isFavorite: isVideoFavorite(video, favorites)
      }
    });`

2021-03-17 16:35 UTC, silviapio commented on src/components/Home.js
> +    setVideos([...videos]);
cierto, se ha quedado así seguramente al modificar la función. gracias!

2021-03-17 16:39 UTC, silviapio commented on src/components/Home.js
> +  useEffect(() => localStorage.setItem("savedSearches", JSON.stringify(searchHistory)), [searchHistory]);
sí, la había hecho (ya tengo una que sirve para sincronizar al cargar o recargar la página), pero finalmente no me ahorraba mucho código, y la borré :-(

2021-03-17 16:44 UTC, silviapio commented on src/components/Home.js
> +            id: { videoId: videoItem.id }
sí, es raro, pero tiene motivación: si el usuario no ha realizado búsquedas aún, se cargan los videos "recommended" (o "most popular" como quieras llamarlos), y la respuesta de la API tiene esta estructura:
`"items": [
        {
            "kind": "youtube#video",
            "etag": "LX9idQ_g3Pqztmrht-7QWRSGKR4",
            "id": "9rhadTURsrw",`
mientras que en todas las otras llamadas devuelve:
`"items": [
        {
            "kind": "youtube#searchResult",
            "etag": "NoDZGJoSW5MlRaAB2p8tiBfwZ20",
            "id": {
                "kind": "youtube#video",
                "videoId": "A_HjMIjzyMU"
            },`
así que sin esta estructura, luego falla la app al pasar los ids. Es raro sí, pero es lo único que se me ha ocurrido!

2021-03-20 22:58 UTC, silviapio commented on src/components/Home.js
> +        videoList.forEach(video => {
ok. aquí también he usado isVideoFavorite() como en el comentario anterior!

2021-03-20 23:01 UTC, silviapio commented on src/components/Home.js
> +  }
ok

2021-03-20 23:01 UTC, silviapio commented on src/components/Home.js
> +  }
ok

2021-03-20 23:04 UTC, silviapio commented on src/components/Home.js
> +            className="horizontal5home"  />
ok

2021-03-20 23:04 UTC, silviapio commented on src/components/Home.js
> +            loading={isLoading}
cierto!

2021-03-20 23:05 UTC, silviapio commented on src/components/Home.js
> +                {searchHistory.map( (historyEntry, i) =>
ok

2021-03-20 23:16 UTC, silviapio commented on src/components/Menu.js
> +            <Link to='/favorites'>
ok

2021-03-20 23:17 UTC, silviapio commented on src/components/SearchBar.js
> +                disabled={loading} />
ok!

2021-03-20 23:18 UTC, silviapio commented on src/components/SearchBar.styles.js
> +
ok!

2021-03-20 23:24 UTC, silviapio commented on src/components/SearchHistory.js
> +        let videosToDisplay;
Cierto, ha quedado mucho mejor así. Gracias!

2021-03-20 23:37 UTC, silviapio commented on src/components/SearchHistory.js
> +        recentlyViewed.forEach(video => {
ok, hecho

2021-03-20 23:37 UTC, silviapio commented on src/components/SearchHistory.js
> +        setRecentlyViewed([
ok, corregido en ambos

2021-03-20 23:38 UTC, silviapio commented on src/components/SearchHistory.js
> +      }
cierto!

2021-03-20 23:40 UTC, silviapio commented on src/components/SearchHistory.js
> +            {recentlyViewed.length === 0 && lastSearchedVideos.length === 0 ?
ahhhh no había caido en que podía usar el ! .. cierto, corregido!

2021-03-20 23:57 UTC, silviapio commented on src/components/SearchHistoryItem.js
> +const SearchHistoryItem = (props) => {
lo he intentado, pero el problema es que esto `props.videos[0].snippet.thumbnails.default.url`, ya que coge un elemento concreto del array, no lo consigo... :-(

2021-03-20 23:59 UTC, silviapio commented on src/components/VideoDetail.js
> +const VideoDetail = ({ video, video: { id: { videoId }, snippet: { title, description } }, onFavToggle, isFavorite }) => {
ok!

2021-03-21 00:02 UTC, silviapio commented on src/components/VideoDetailPage.js
> +                updatedVideos.unshift(videoToDisplay);
cierto!! no había caído!

2021-03-21 00:06 UTC, silviapio commented on src/components/VideoDetailPage.js
> +            videoList.forEach(video => video.isFavorite = isVideoFavorite(video, favorites));
me tiene que haber gustado mas de la cuenta este forEach ;-) corregido!

2021-03-24 09:39 UTC, silviapio commented on src/components/VideoDetailPage.js
> +    const wasVideoDisplayedAlready = myVideoId => {
wow, es verdad. hecho, gracias!

2021-03-24 09:39 UTC, silviapio commented on src/components/VideoDetailPage.js
> +        .then((response) =>{
ok, cierto

2021-03-24 09:47 UTC, silviapio commented on src/components/VideoList.js
> +    const handleSelect = key => () => {
sin esta, no me funciona, me va en loop...

2021-03-24 09:48 UTC, silviapio commented on src/components/VideoList.js
> +                        onSelect={handleSelect(video.id.videoId)}
lo que decía, sin handleselect con doble arrow function, me va en loop infinito

2022-02-02 13:28 UTC, closed without merging